### PR TITLE
Ignore generated public resources

### PR DESCRIPTION
**Pull request by petersandor**
I believe these two directories are safe to ignore since they contain only resources generated by Gulp

### CODE REVIEW

**Comment by timkurvers** [comment]
Thanks! Could you order them alphabetically? Should `public/templates` be included here too?

**Comment by petersandor** [comment]
Sure, I will order them. And you are right about the `public/templates`. I missed that one since that directory is included in repository. I might as well delete it, if you agree?

**Comment by timkurvers** [comment]
Oh I see. I think the original idea was to at some point version control both scripts and styles too, but they're quite massive. Let's delete/ignore all three directories for now :+1:

**Comment by timkurvers** [comment]
Awesome stuff :+1:

**Pull request merged**
